### ISSUE TITLE
suggestions and typo

### ISSUE THREAD

**Issue by FinalSurgery** [pwolthausen/k8s-workshops#9]
1. Nic and Ashik had issues deploying your setup.sh file because he was not aware that you needed to change all the scripts in the tutorial to be executable. not just the setup.sh.
![Screenshot 2019-11-28 at 4 38 03 PM](https://user-images.githubusercontent.com/58312215/69832634-7bd24f80-11fd-11ea-94a6-17cca42e51a6.png)

2. the setup.sh file contains a typo I.E projecr instead of project.

Hope your new job is great!

**Comment by pwolthausen** [comment]
corrected in latest merge
